title: SuperF4
url: https://stefansundin.github.io
baseurl: /superf4
github_repo: stefansundin/superf4
description: Kill programs instantly with Ctrl+Alt+F4.
author: Stefan Sundin

# posts
permalink: /news/:year-:month-:day-:title.html

# build
markdown: kramdown
kramdown:
  input: GFM
